### ISSUE TITLE
`The specified log group does not exist` message

### ISSUE THREAD

**Issue by thebarty** [howardengelhart/smoketail#3]
I can't get this to work.

The thing is that the log-group DOES exist, BUT

running `node_modules/.bin/smoketail -f /aws/lambda/lambda-experts-form` gives me a
```
The specified log group does not exist.
```

while running `aws logs filter-log-events --log-group-name /aws/lambda/lambda-experts-form`
shows me the logs.

Any ideas?

**Comment by ThomasAndrewMacLean** [comment]
hi, had the same problem at first, setting the region got it working for me
 -r eu-west-1

**Comment by howardengelhart** [comment]
@thebarty - Apologies for the delayed response.  I wasn't getting emails from github for issues.  Not sure if @ThomasAndrewMacLean 's suggestion helped you out.  Another potential cause could be authentication, particularly if you are accessing more than one AWS account, or using multiple credentials.  I'm working on an update now that will allow a named profile (as found in ~/.aws/credentials) to be used when running the cli.
